<?php

class Db_Query extends Module {

    /**
     * Stores the current models table name, generated by the _getTableName method.
     */
    private $_table         = null;

    /**
     * Stores the class name of the model.
     */
    private $_class         = null;

    /**
     * The following properties hold strings related to methods run in this
     * class. They are used to build queries.
     */
    private $_select        = '';
    private $_distinct      = false;
    private $_from          = '';
    private $_join          = '';
    private $_where         = '';
    private $_orderBy       = '';
    private $_limit         = '';
    private $_search        = ''; // Fulltext
    private $_bindings      = array();

    /**
     * Because Caffeine may call the describe method multiple times, we
     * store the value of each describe method for each model so its
     * only queries once. See the describe() method for details.
     */
    private static $_describes  = array();

    /**
     * As as the above describe property, multiple calls may be made.
     * Store their values to avoid uneeded queries. See the exists() 
     * method for details.
     */
    private static $_exists     = array();

    /**
     * Can be set in a model to specify wether to automatically create
     * an auto incremented primary id. This is the default.
     */
    protected $_createId    = true;

    /**
     * Can be set to automatically create the "created_at" and "updated_at"
     * fields in a models table. In addition, each query that inserts or modifies
     * a table, the two timestamp fields will be updated automatically.
     */
    protected $_timestamps  = false;

    /**
     * An array of table fields to create, see documentation for full syntax.
     *
     * Example: 
     *      $_fields = array(
     *          'title' => array(
     *              'type' => 'varchar',
     *              'length' => 255,
     *              'not null' => true
     *          )
     *      );
     */
    protected $_fields      = array();

    /**
     * An array of field names to create indexes for.
     */
    protected $_indexes     = array();

    /**
     * An array of field names to create fulltext indexes for.
     */
    protected $_fulltext    = array();

    /**
    NOT CURRENTLY USED, WILL BE USED WHEN PROPER ORM IS WRITTEN
    protected $_hasOne      = array(); 
    protected $_hasMany     = array();
    */

    /**
     * An array of models that the current model is related to. This will
     * automatically create foreign key fields based on the model names
     * in the array.
     *
     * Example:
     *      $_indexes = array('module.model');
     *
     *      blog.post creates the field "post_id"
     *      media.file creates the field "field_id"
     */
    protected $_belongsTo   = array();

    /**
     * An array of models that this model has a many-to-many relationship
     * with. The syntax is the same as the above $_belongsTo property.
     *
     * See the Db_Runner::_createHABTM() method for details on how a many-to-many
     * table is created and named.
     */
    protected $_hasAndBelongsToMany = array();

    /**
     * Allow read access to private properties.
     */
    public function __get($name) {
        return $this->{$name};
    }
    
    /**
     * TODO Comments
     */
    public function __construct($table = null)
    {
        if(!is_null($table))
            $this->_table = $table;

        if(is_null($this->_table))
            $this->_table = $this->_getTableName();

        $this->_from = sprintf(' FROM %s', $this->_table);

        // Produce query results that are of the same class as this model
        $this->_class = get_called_class(); 
    }

    /**
     * Adds a new table index to the end of the index array.
     */
    public function addIndex($key) {
        array_push($this->_indexes, $key);
    }

    /**
     * TODO Comments
     */
    public function select()
    {
        $args = func_get_args();

        // Only generate select if it wasn't done previously, or if new params were passed (via first(), get() etc.)
        if(!strlen($this->_select) || $args)
        {
            $this->_select = ($this->_distinct) ? 'SELECT DISTINCT ' : 'SELECT ';
            $this->_select .= ($args) ? implode(', ', $args) : '*'; 
        }

        return $this;
    }

    /**
     * TODO Comments
     */
    public function insert($data, $getInsertId = true)
    {
        $columns = array();
        $values = array();

        if($this->_timestamps)
        {
            $timestamp = time();
            $data['created_at'] = $timestamp;
            $data['updated_at'] = $timestamp;
        }

        foreach($data as $c => $v)
        {
            $columns[] = $c;
            $values[] = $v;
        }

        $sql = sprintf('INSERT INTO %s (%s) VALUES (%s)', 
            $this->_table, 
            implode(', ', $columns),
            rtrim(str_repeat('?, ', count($values)), ', ')
        );

        return Db::query($sql, $values, $getInsertId);
    }

    /**
     * TODO Comments
     */
    public function update($data)
    {
        $columns = array();
        $values = array();

        if($this->_timestamps)
            $data['updated_at'] = time();

        foreach($data as $c => $v)
        {
            $columns[] = $c . ' = ?';
            $values[] = $v;
        }

        $values = array_merge($values, $this->_bindings);
        $sql = sprintf('UPDATE %s SET %s %s', $this->_table, implode(', ', $columns), $this->_where);

        return Db::query($sql, $values);
    }

    /**
     * TODO Comments
     */
    public function delete($id = null)
    {
        if(!is_null($id))
            $this->where('id', '=', $id);

        if(strlen($this->_where))
            $sql = sprintf('DELETE%s%s', $this->_from, $this->_where);
        else
            $sql = sprintf('TRUNCATE TABLE %s', $this->_table);

        return Db::query($sql, $this->_bindings);
    }

    /**
     * TODO Comments
     */
    public function truncate()
    {
        $this->_where = '';
        return $this->delete();
    }

    /**
     * TODO Comments
     */
    public function describe() 
    {
        if(!isset(self::$_describes[$this->_table]))
        {
            if($this->exists())
            {
                $data = Db::query('DESCRIBE ' . $this->_table);

                // Only store a describe if it returns data, otherwise the table probably wasn't created yet
                if($data)
                    self::$_describes[$this->_table] = $data;
                else
                    return $data;
            }
            else
                return null;
        }

        return self::$_describes[$this->_table];
    }

    /**
     * Determines if a table exists. After this first call to this, the response is stored
     * to avoid multiple, unecessary calls to the database.
     *
     * @param boolean $force Forces the query to be run, regardless if its been run before.
     */
    public function exists($force = false)
    {
        if(!isset(self::$_exists[$this->_table]) || $force)
            self::$_exists[$this->_table] = Db::query('SHOW TABLES LIKE \'' . $this->_table . '\'');

        return self::$_exists[$this->_table];
    }

    /**
     * TODO Comments
     */
    public function distinct()
    {
        $this->_distinct = true;
        return $this;
    }

    /**
     * Regular SELECT query. If no other options are set, this will get all
     * records from the current table.
     *
     * Can specify params of fields to get. If no params are set, all fields
     * will be returned.
     *
     * Examples:
     *
     * Db()->table('users')->get(); // Get all records and all fields
     * Db()->table('users')->get('first_name', 'age'); // Only two fields
     */
    public function get()
    {
        call_user_func_array(array($this, 'select'), func_get_args());

        $sql = $this->_select . 
            $this->_from . 
            $this->_join . 
            $this->_where . 
            $this->_search .
            $this->_orderBy .
            $this->_limit;

        return Db::query($sql, $this->_bindings, false, $this->_class);
    }

    /**
     * Alias of get()
     */
    public function all() {
        return $this->get();
    }

    /**
     * Returns the first result from a query. 
     *
     * Examples:
     *
     * Db()->table('users')->first();
     */
    public function first()
    {
        $this->limit(1);
        $results = call_user_func_array(array($this, 'get'), func_get_args());
        if($results)
            return array_shift($results);
        return false;
    }

    /**
     * Finds a single record based on an id or slug. If an int is passed its
     * assumed to be an id. Anything not an int is considered a slug.
     */
    public function find($idOrSlug)
    {
        $type = (is_numeric($idOrSlug)) ? 'id' : 'slug'; // Need to use is_numeric because is_int wont work with strings (ex: "12")
        return $this->where($type, '=', $idOrSlug)->first();
    }

    /**
     * Counts the number of records returned from the query
     *
     * Examples:
     *
     * Db()->get('users')->count(); // Count all records
     * Db()->get('users')->where('age', '>', '23')->count()
     */
    public function count($column = '*') {
        return $this->select(sprintf('COUNT(%s) AS count', $column))->first()->count;
    }

    /**
     * TODO Comments
     */
    public function orderBy($column, $direction = 'ASC')
    {
        if(!strlen($this->_orderBy))
            $this->_orderBy = ' ORDER BY';
        else
            $this->_orderBy .= ',';

        $this->_orderBy .= sprintf(' %s %s', $column, strtoupper($direction));
        return $this;
    }

    /**
     * TODO Comments
     */
    public function limit($limit, $offset = null)
    {
        if(is_null($offset))
            $this->_limit = sprintf(' LIMIT %d', $limit);
        else
            $this->_limit = sprintf(' LIMIT %d, %d', $offset, $limit);

        return $this;
    }

    /**
     * Starts a where clause. 
     *
     * Examples:
     *
     * Db::table('users')->where('name', 'LIKE', 'Bob')->get();
     * Db::table('users')->where('email', '=', 'bob@example.com')->first();
     */
    public function where($column, $operator, $value, $modifier = null)
    {
        if(is_null($modifier))
            $this->_where = sprintf(' WHERE %s %s ?', $column, $operator);
        else
            $this->_where .= sprintf(' %s %s %s ?', $modifier, $column, $operator);

        $this->_bindings[] = $value;
        return $this;
    }

    /**
     * TODO Comments
     */
    public function andWhere($column, $operator, $value)
    {
        $this->where($column, $operator, $value, 'AND');
        return $this;
    }

    /**
     * TODO Comments
     */
    public function orWhere($column, $operator, $value)
    {
        $this->where($column, $operator, $value, 'OR');
        return $this;
    }

    /**
     * Does an inner join on a table. The first param is the table to join, the
     * last 3 params are used to create the ON statement.
     *
     * Examples:
     *
     * DB::table('users')->join('photos', 'photos.user_id', '=', 'user.id')->get();
     */
    public function join($table, $column1, $operator, $column2, $modifier = 'INNER')
    {
        $this->_join .= sprintf(' %s JOIN %s ON %s %s %s', 
            $modifier, $table, $column1, $operator, $column2);

        return $this;
    }

    /**
     * TODO Comments
     */
    public function leftJoin($table, $column1, $operator, $column2)
    {
        return $this->join($table, $column1, $operator, $column2, 'LEFT');
    }

    /**
     * TODO Comments
     */
    public function fulltext($match, $against, $boolean = false)
    {
        if(is_array($match))
            $match = implode(',', $match);

        $boolean = $boolean ? ' IN BOOLEAN MODE' : '';

        $this->_search = sprintf(' WHERE MATCH(%s) AGAINST(?%s)', $match, $boolean);
        $this->_bindings[] = $against;

        return $this;
    }

    /**
     * Alias of fulltext()
     */
    public function search($match, $against, $boolean = false) {
        return $this->fulltext($match, $against, $boolean);
    }

    /**
     * Determines the tables name based on the class name. The table name will be
     * the module name, an underscore and the model name in plural form.
     *
     * Example: Blog_PostModel = blog_posts
     */
    private function _getTableName()
    {
        $class = get_called_class();
        $bits = explode('_', $class);
        $model = sprintf('%s_%s', 
            strtolower($bits[0]), 
            str_replace('model', '', strtolower($bits[1]))
        );

        return String::plural($model);
    }

}
